### PR TITLE
Add a feedback button to records

### LINKED ISSUE #146: Suggest UI design for flagging "bad" records
Perhaps borrowing heavily from Revs?

### PR DESCRIPTION
**Pull request by jkeck**
## Why was this change made?
Closes #146

## Was the documentation (README, API, wiki, ...) updated?

https://user-images.githubusercontent.com/96776/105427725-9b4ae980-5c02-11eb-99d4-fe1169339064.mov

Resulting email:

```
To: test@example.com
Cc: test@example.com
Message-ID: <600a16a99bb2e_12b0122588933a1@li-dl-7475-708c.local.mail>
Subject: DLME item feedback
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <p></p>
<p>From: &quot;&quot; &lt;&gt;</p>

<p>This site is great, and this record in particular is REALLY good!</p>

----

<dl>
  <dt>REMOTE_IP</dt><dd>::1</dd>
  <dt>USER AGENT</dt><dd>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36</dd>
  <dt>EXHIBIT</dt><dd>Test Exhibit</dd>
  <dt>CURRENT_URL</dt><dd>http://localhost:3000/en/test-exhibit/catalog/b17775905</dd>
  <dt>UUID</dt><dd>5cc49814-35b6-4f2a-aafd-8ae6b7ab5d06</dd>
</dl>
  </body>
</html>
```

### CODE REVIEW

**Comment by jkeck** [comment]
Is this looking right for the Feedback button in RTL @ggeisler / @jacobthill 

Screen Shot 2021-01-21 at 4 02 53 PM

**Comment by ggeisler** [comment]
@jkeck I'm going to defer to @jacobthill on the RTL question (I think so?) but the rest looks great.

Minor, possibly irrelevant point: the suggested subject line for the email was:

> DLME item feedback

(Not sure if that is part of this work or not, but I noticed in your resulting email example it didn't match that.)

**Comment by jkeck** [comment]
@ggeisler 👍  good catch.  The code says that it's the `application_name` but looking deeper, it prefers exhibit title.  I'll fix that.

**Review by cbeer — APPROVED** [review]

**Comment by jacobthill** [comment]
I think the feedback label looks like its supposed to.

**Pull request merged**
