### PR TITLE
Move transform data/results to tabs

### LINKED ISSUE #469: Add styling/UX improvements to transform pages
Current state:

**Transform data**

screen shot 2019-03-05 at 10 26 21 am

* Add header that says Transform data
* After clicking "Begin transform" I should be taken back to the Transform data page, with a flash message that the transform has been started (#455)
* Add tabbed view to separate Transform data/Transform results?

### PR DESCRIPTION
**Pull request by jcoyne**
Fixes #469

### CODE REVIEW

**Comment by justinlittman** [comment]
I defer to your judgement as tech lead, but client-side JS does not seem like the simplest possible solution to the requirements and will be more problematic to maintain.

**Comment by jcoyne** [comment]
@justinlittman client side JS is already a part of this project.  This JS adds no dependencies. My thoughts are that we should do as much as we can to push presentation logic to the front end and keep business logic in the backend.

**Comment by justinlittman** [comment]
`docker-compose build app` results in:
```
I, [2019-03-11T16:11:41.077515 #7]  INFO -- : Writing /opt/public/assets/favicon-b4185c7dd08c0b4f2142c58bbcca322b3a01f50adc3413438b98be2b664bb4b6.ico
I, [2019-03-11T16:11:41.078685 #7]  INFO -- : Writing /opt/public/assets/favicon-b4185c7dd08c0b4f2142c58bbcca322b3a01f50adc3413438b98be2b664bb4b6.ico.gz
I, [2019-03-11T16:11:41.084526 #7]  INFO -- : Writing /opt/public/assets/layers-2x-066daca850d8ffbef007af00b06eac0015728dee279c51f3cb6c716df7c42edf.png
I, [2019-03-11T16:11:41.088897 #7]  INFO -- : Writing /opt/public/assets/layers-1dbbe9d028e292f36fcba8f8b3a28d5e8932754fc2215b9ac69e4cdecf5107c6.png
I, [2019-03-11T16:11:41.093029 #7]  INFO -- : Writing /opt/public/assets/marker-icon-2x-00179c4c1ee830d3a108412ae0d294f55776cfeb085c60129a39aa6fc4ae2528.png
I, [2019-03-11T16:11:41.097892 #7]  INFO -- : Writing /opt/public/assets/marker-icon-574c3a5cca85f4114085b6841596d62f00d7c892c7b03f28cbfa301deb1dc437.png
I, [2019-03-11T16:11:41.101644 #7]  INFO -- : Writing /opt/public/assets/marker-shadow-264f5c640339f042dd729062cfc04c17f8ea0f29882b538e3848ed8f10edb4da.png
I, [2019-03-11T16:11:41.105275 #7]  INFO -- : Writing /opt/public/assets/spotlight/default_thumbnail-bbab04087becfd4290ed6cae8bb3ef4fdf2b86389fc11a59c14950cff0b6f256.jpg
I, [2019-03-11T16:11:41.108944 #7]  INFO -- : Writing /opt/public/assets/spotlight/default_browse_thumbnail-6f9bd62b551a84b2f8318935afbd33fceb95e366ab701d7fba2dd0ec7416efa9.jpg
I, [2019-03-11T16:11:41.111830 #7]  INFO -- : Writing /opt/public/assets/default-52adc3dc03639885e8aa93763e29868269dd3b9dad4689f140c0175b4f945922.png
I, [2019-03-11T16:11:41.114360 #7]  INFO -- : Writing /opt/public/assets/email-icon-d103d4646c00970c8e2ec43c4077cd53518f2cde02f1a7a14ed0c7327ce9a28c.png
I, [2019-03-11T16:11:41.116825 #7]  INFO -- : Writing /opt/public/assets/github-icon-a4b257a1951f0ae83ccedb7e39c95563c375eff54d7b1784e9ce2132796aca8e.png
I, [2019-03-11T16:11:41.119134 #7]  INFO -- : Writing /opt/public/assets/twitter-icon-35627cacc15c5e7956c6f44004dbc6d1077fe3a9229f237aa15b96122229e414.png
rake aborted!
Uglifier::Error: Unexpected token: name (TransformStatus). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
/usr/local/bundle/gems/uglifier-4.1.20/lib/uglifier.rb:234:in `parse_result'
/usr/local/bundle/gems/uglifier-4.1.20/lib/uglifier.rb:216:in `run_uglifyjs'
/usr/local/bundle/gems/uglifier-4.1.20/lib/uglifier.rb:168:in `compile'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/usr/local/bundle/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/usr/local/bundle/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by jcoyne** [comment]
Gah! Uglifier 😡

**Comment by justinlittman** [comment]
Waiting for dev environment to come back up ...

**Comment by justinlittman** [comment]
Screen Shot 2019-03-14 at 7 55 03 AM

There's an alignment issue and an errant comma.

**Comment by justinlittman** [comment]
And null shown when no errors:
Screen Shot 2019-03-14 at 11 13 14 AM

**Comment by justinlittman** [comment]
And when user is on the Transform results tab and hits refresh (to see if a transform is completed), user is returned is Transform data tab.

User should be returned to Transform results tab or Transform results should update async.

**Comment by jcoyne** [comment]
@justinlittman I think that's how bootstrap tabs work. This is consistent with the behavior on this page too: https://spotlight.dev.dlmenetwork.org/site/edit

**Comment by justinlittman** [comment]
I defer to @jacobthill but it seems to defeat the purpose of fewer clicks if you need to switch tabs whenever you refresh waiting for your transform to complete.

Or perhaps switch the tabs so the result is the default?

**Comment by jcoyne** [comment]
I've updated so that the results tab is the default tab.

**Pull request merged**
