### PR TITLE
[HOLD] add Arabic UI labels for spotlight, closes #541

### LINKED ISSUE #541: Translate spotlight & blacklight UI labels into Arabic
Requirements:
- [ ] get English UI labels to translators (Blacklight & Spotlight)
- [ ] get Arabic translation from translators
- [ ] store translated labels in [yaml file](https://github.com/projectblacklight/spotlight/blob/master/config/locales/spotlight.it.yml)

### PR DESCRIPTION
**Pull request by jacobthill**
## Why was this change made?
Add the Arabic spotlight UI labels for Arabic interfaces

## Was the documentation (README, API, wiki, ...) updated?
NA

### CODE REVIEW

**Comment by jacobthill** [comment]
No, I'm not sure how to run it locally. I think another developer may need to help with that. I took the italian file and replace the Italian language portion with Arabic and changed line 1 from "it:" to "ar:". Let me know if I need to pair with someone.

**Comment by aaron-collier** [comment]
I'll pull it down and test. First reason I ask is that I don't see any other spotlight.*.yml locale files.

**Comment by jacobthill** [comment]
My instinct is that those are used only for translation and DLME hasn't done that yet. I followed the path used with the Italian translation provided by Gary "https://github.com/projectblacklight/spotlight/blob/master/config/locales/spotlight.it.yml"

**Comment by ggeisler** [comment]
@jacobthill @aaron-collier I wonder if this PR would be better in https://github.com/projectblacklight/spotlight instead?

I'm not sure if DLME if locked to a certain release of Spotlight, but if not I think adding the Arabic locale file to Spotlight, rather than DLME directly, would benefit the larger Spotlight community (and our local Stanford exhibits) by making the Arabic translations available in Spotlight itself. DLME would then inherit them from Spotlight.

DLME wouldn't get the translations until we cut a new release of Spotlight, but I am hoping we will do that in the next week or so, because I've added a French locale file we need for the French Revolution exhibit that is under construction.

**Comment by jacobthill** [comment]
Yeah, that probably makes sense. I’ll submit a PR after lunch.

**Comment by jacobthill** [comment]
@ggeisler Looks like I don't have permission to push to the spotlight repo.

**Comment by ggeisler** [comment]
@jacobthill Can you fork the Spotlight repo and submit a PR that way? That shouldn't require any permissions.

**Pull request closed without merging**
