### PR TITLE
Refactor the TransformController

### PR DESCRIPTION
**Pull request by jcoyne**
Rails knows how to parse JSON responses.  Also changed to a request
test.

### CODE REVIEW

**Comment by jcoyne** [comment]
@justinlittman is it possible it's not setting the `Content-type` header?

**Comment by jcoyne** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=69413 😢

**Comment by justinlittman** [comment]
Possible, but not according to the docs: https://docs.aws.amazon.com/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html

**Comment by justinlittman** [comment]
Hah, a thread about a minor bug that started in 2011.

**Pull request merged**
