### PR TITLE
Upgrade to rails 7.1

### PR DESCRIPTION
**Pull request by jcoyne**
This needs to run `bin/rails active_storage:update` before being complete, but it's running into trouble:
```
bin/rails active_storage:update
DEPRECATION WARNING: DeprecatedConstantProxy without a deprecator is deprecated (called from <main> at /Users/jcoyne85/workspace/sul-dlss/dlme/config/application.rb:7)
DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.

Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format
for more information on how to upgrade.
 (called from <main> at /Users/jcoyne85/workspace/sul-dlss/dlme/config/environment.rb:5)
      PaperTrail 12.3.0 is not compatible with ActiveRecord 7.1.2. We allow PT
      contributors to install incompatible versions of ActiveRecord, and this
      warning can be silenced with an environment variable, but this is a bad
      idea for normal use. Please install a compatible version of ActiveRecord
      instead (>= 5.2, < 7.1). Please see the discussion in paper_trail/compatibility.rb
      for details.
bin/rails aborted!
NoMethodError: undefined method `arity' for an instance of Hash (NoMethodError)

      if scope && scope.arity == 0
                       ^^^^^^
/Users/jcoyne85/workspace/sul-dlss/dlme/app/models/solr_document.rb:7:in `<class:SolrDocument>'
/Users/jcoyne85/workspace/sul-dlss/dlme/app/models/solr_document.rb:4:in `<main>'
/Users/jcoyne85/workspace/sul-dlss/dlme/config/initializers/okcomputer.rb:4:in `block in <main>'
/Users/jcoyne85/workspace/sul-dlss/dlme/config/environment.rb:5:in `<main>'
Tasks: TOP => active_storage:update => environment
```

### CODE REVIEW

**Comment by jcoyne** [comment]
@corylown we probably don't want the `db/` files in here.

**Comment by corylown** [comment]
> @corylown we probably don't want the `db/` files in here.

We definitely don't. They're removed.

**Comment by corylown** [comment]
I think we're now on a version of papertrail that's compatible with Rails 7.1: https://github.com/paper-trail-gem/paper_trail/blob/v15.1.0/README.md#1a-compatibility

**Comment by corylown** [comment]
Updating to spotlight >= 3.6.0.beta8 should fix the test failure because https://github.com/projectblacklight/spotlight/commit/b51a8ac88215651baec344cbfda8312b1e746bc5 is included.

PR to update spotlight: https://github.com/sul-dlss/dlme/pull/1868/files

**Pull request merged**
